Dolphiny/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('be_instructor/', user_views.beinstructor, name='be-instructor'),
    path('be_student/', user_views.bestudent, name='be-student'),
    path('team/', user_views.team, name='team'),
    path('contact/', user_views.contact, name='contact'),
    path('profile/update/', login_required(user_views.profileupdate), name='profile_update'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='blog/landing-page.html'), name='logout'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path
from .views import (
    DomainListView,
    CourseListView,
    CourseDetailView,
    CourseCreateView,
    CourseUpdateView,
    CourseDeleteView,
    DomainCourseListView, ProfileListView, SectionDetailView, CourseEnrolledDetailView, InstructorCourseListView,
    UserCourseListView, SectionUpdateView
)
from . import views

urlpatterns = [
    path('', views.landing, name='landing-page'),
    path('domain/', DomainListView.as_view(), name='domain-page'),
    path('profile/',  login_required(ProfileListView.as_view()), name='profile-page'),
    path('search/', views.searchCourses, name='search-course'),
    path('course/', CourseListView.as_view(), name='course-page'),
    path('created_courses/', InstructorCourseListView.as_view(), name='created_courses'),
    path('Mycourses/', UserCourseListView.as_view(), name='Mycourses'),
    path('dashboard/', views.dashData, name='dashboard'),
    path('domain/<str:domainId>/course/', DomainCourseListView.as_view(), name='domain-courses'),
    path('course_detail/<int:pk>/', views.coursdetail, name='course-detail'),
    path('course_enrolled_detail/<int:pk>/', CourseEnrolledDetailView.as_view(), name='course-enrolled-detail'),
    path('section/<int:pk>/', SectionDetailView.as_view(), name='section-detail'),
    path('course/<int:pk>/new-section/', views.createSection, name='section-create'),
    path('section/<int:pk>/update/', SectionUpdateView.as_view(), name='section-update'),
    path('course/new/', views.createCourse, name='course-create'),
    path('course/<int:pk>/update/', CourseUpdateView.as_view(), name='course-update'),
    path('course/<int:pk>/delete/', CourseDeleteView.as_view(), name='course-delete'),
    path('about/', views.about, name='dolphiny-about'),
    path('checkout/<int:pk>/', views.checkout, name="checkout"),
    path('complete/', views.paymentComplete, name="complete"),

]

blog/models.py
from django.db import models
from django.utils import timezone
from users.models import CustomUser as User
from django.urls import reverse
from .validators import validate_video


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})


class Domain(models.Model):
    domainId = models.CharField(primary_key=True, max_length=15)
    title = models.CharField(max_length=255)
    image = models.ImageField(default='default.jpg', upload_to='domain_images')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('domain-courses', kwargs={'domainId': self.domainId})


class Student(models.Model):
    studentId = models.CharField(primary_key=True, max_length=10)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    degree = models.CharField(max_length=15)
    university = models.CharField(max_length=50)
    linkedIn = models.URLField(blank=True, null=True)
    verified = models.BooleanField(default=False)


class Instructor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    domainId = models.ForeignKey(Domain, on_delete=models.PROTECT)
    verified = models.BooleanField(default=False)
    company = models.CharField(max_length=100)
    linkedIn = models.URLField(unique=True)
    diploma = models.ImageField(default='default.jpg', upload_to='deploma_pics')


class Course(models.Model):

    instructor = models.ForeignKey(Instructor, on_delete=models.CASCADE)
    domainId = models.ForeignKey(Domain, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='course_image')
    title = models.CharField(max_length=100)
    description = models.TextField()
    duration = models.DurationField()
    creationDate = models.DateTimeField(default=timezone.now)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    level = models.CharField(max_length=100)
    you_will_learn = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('course-detail', kwargs={'pk': self.pk})


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    idCours = models.ForeignKey(Course, on_delete=models.PROTECT)
    date = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    enroll = models.BooleanField(default=False)


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idCours = models.ForeignKey(Course, on_delete=models.CASCADE)
    enumerate = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]
    Rate = models.CharField(
        max_length=2,
        choices=enumerate,
        null=True,
        blank=True
    )


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idCours = models.ForeignKey(Course, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    comment = models.TextField()


class Replie(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    idComment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    reply = models.TextField(default='default reply')


class Section(models.Model):
    idCours = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.CharField(default=idCours, max_length=100)
    description = models.TextField()
    media = models.FileField(upload_to="videos", validators=[validate_video])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('section-detail', kwargs={'pk': self.pk})

blog/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import JsonResponse
import json
from operator import attrgetter
from django.urls import reverse
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)

from users.models import CustomUser
from .forms import CourseCreateForm, AddComment, SectionCreateForm
from .models import (
    Course,
    Domain, Section, Payment, Comment, Student, Instructor,
)


def landing(request):
    return render(request, "blog/landing-page.html")


"""def domain.css(request):
    context = {
        'domains': Domain.objects.all()
    }
    return render(request, "blog/domain.css.html", context)"""

"""def course(request, domainid):
    context = {
        'courses': Course.objects.filter(domainId=domainid)
    }
    return render(request, "blog/home.html", context)"""


def searchCourses(request):
    context = {}
    if request.method == 'GET':
        search = request.GET['searched']
        queries = search.split(" ")
        queryset = []
        for q in queries:
            courses = Course.objects.filter(
                Q(title__icontains=q) |
                Q(description__icontains=q) |
                Q(you_will_learn__icontains=q) |
                Q(level__icontains=q) |
                Q(price__icontains=q)).distinct()

            for course in courses:
                queryset.append(course)
        courses = sorted(list(set(queryset)), key=attrgetter('creationDate'), reverse=True)
        context['searched'] = str(search)
        context['courses'] = courses
    return render(request, 'blog/search_courses.html', context)


class DomainListView(ListView):
    model = Domain
    template_name = 'blog/domain.html'
    context_object_name = 'domains'
    ordering = ['title']
    # paginate_by = 5


class CourseListView(ListView):
    model = Course
    template_name = 'blog/course.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'courses'
    ordering = ['-creationDate']


class InstructorCourseListView(ListView):
    model = Course
    template_name = 'blog/Instructor_courses.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'courses'
    ordering = ['-creationDate']

    def get_queryset(self):
        return Course.objects.filter(instructor=self.request.user.instructor)


class UserCourseListView(ListView):
    model = Payment
    template_name = 'blog/user_courses.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'courses'
    ordering = ['-creationDate']

    def get_queryset(self):
        return Payment.objects.filter(user=self.request.user)


class ProfileListView(ListView):
    model = CustomUser
    template_name = 'users/profile.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'user'
    ordering = ['-creationDate']

    def get_queryset(self):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['courses'] = Payment.objects.filter(user=self.request.user)
        return context


class CourseDetailView(DetailView):
    template_name = 'blog/couse_detail.html'
    model = Course

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = get_object_or_404(Course, pk=self.kwargs.get('pk'))
        context['sections'] = Section.objects.filter(idCours=course)
        return context


class DomainCourseListView(ListView):
    model = Course
    template_name = 'blog/domain_courses.html'
    context_object_name = 'courses'
    ordering = ['-creationDate']

    # paginate_by = 5
    def get_queryset(self):
        domainid = get_object_or_404(Domain, domainId=self.kwargs.get('domainId'))
        return Course.objects.filter(domainId=domainid).order_by('-creationDate')


class SectionCourseListView(ListView):
    model = Section
    template_name = 'blog/section_course.html'  # <app>/<model>_<viewtype>.html
    context_object_name = 'sections'
    paginate_by = 5

    @property
    def get_queryset(self):
        course = get_object_or_404(Course, idCours=self.kwargs.get('idCours'))
        return Section.objects.filter(idCours=course).order_by("title")


class SectionDetailView(DetailView):
    model = Section
    template_name = 'blog/section.html'
    context_object_name = 'section'

    def get_queryset(self):
        section = get_object_or_404(Section, pk=self.kwargs.get('pk'))
        return Section.objects.filter(pk=section.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        section = get_object_or_404(Section, pk=self.kwargs.get('pk'))
        context['object'] = section.idCours
        return context


class CourseEnrolledDetailView(DetailView):
    model = Course
    template_name = 'blog/couse_enrolled_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = get_object_or_404(Course, pk=self.kwargs.get('pk'))
        context['sections'] = Section.objects.filter(idCours=course)
        return context


class CourseCreateView(LoginRequiredMixin, CreateView):
    model = Course
    template_name = "blog/create_course.html"
    fields = ['instructor', 'domainId', 'title', 'image', 'description', 'duration', 'price', 'level', 'you_will_learn']

    def form_valid(self, form):
        form.instance.user = self.request.user.instructor
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('course-detail', kwargs={'pk': self.object.pk})


def createCourse(request):
    if request.method == 'POST':
        form = CourseCreateForm(request.POST,
                                request.FILES)

        form.fields["instructor"].initial = request.user.instructor
        form.fields["instructor"].disabled = True
        if form.is_valid():
            form.save()
            return redirect('created_courses')
    else:
        form = CourseCreateForm(instance=request.user)
        form.fields["instructor"].initial = request.user.instructor
        form.fields["instructor"].disabled = True
    return render(request, 'blog/create_course.html', {'form': form})


def createSection(request, pk):
    course = Course.objects.get(pk=pk)
    if request.method == 'POST':
        form = SectionCreateForm(request.POST,
                                request.FILES)

        form.fields["idCours"].initial = course
        form.fields["idCours"].disabled = True
        if form.is_valid():
            form.save()
            return redirect('course-detail', pk=pk)
    else:
        form = SectionCreateForm()
        form.fields["idCours"].initial = course
        form.fields["idCours"].disabled = True
    return render(request, 'blog/create_section.html', {'form': form})


class SectionUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Section
    fields = [ 'title', 'description', 'media']
    template_name = 'blog/update_section.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        section = self.get_object()
        if self.request.user == section.idCours.instructor.user:
            return True
        return False


class CourseUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Course
    fields = ['title', 'image', 'description', 'duration', 'price', 'level', 'you_will_learn']
    template_name = 'blog/update_course.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        course = self.get_object()
        if self.request.user == course.instructor.user:
            return True
        return False


def coursdetail(request, pk):
    course = Course.objects.get(pk=pk)
    comments = Comment.objects.filter(idCours=course)
    sections = Section.objects.filter(idCours=course)
    enroll = Payment.objects.filter(idCours=course, user=request.user)

    if request.method == 'POST':
        form = AddComment(request.POST)
        form.fields["user"].initial = request.user
        form.fields["idCours"].initial = course

        if form.is_valid():
            comm = request.POST['comment']
            form.fields["comment"] = comm
            print(comm)
            form.save()
            return redirect('course-detail', pk=pk)

    else:
        form = AddComment(instance=request.user)
        form.fields["user"].initial = request.user
        form.fields["idCours"].initial = course

    context = {
        "course": course,
        "sections": sections,
        "enroll": enroll,
        "comments": comments,
        "form": form,
    }
    return render(request, 'blog/couse_detail.html', context)


class CourseDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Course
    success_url = '/'

    def test_func(self):
        course = self.get_object()
        if self.request.user == course.user:
            return True
        return False


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


def paymentComplete(request):
    body = json.loads(request.body)
    print('BODY:', body)
    course = Course.objects.get(id=body['courseId'])
    Payment.objects.create(
        idCours=course,
        user=request.user
    )

    return JsonResponse('Payment completed!', safe=False)


def checkout(request, pk):
    course = Course.objects.get(id=pk)
    context = {'course': course,
               }
    return render(request, 'blog/checkout.html', context)


def dashData(request):
    numcoursres = []
    numenrolls = []
    domains = Domain.objects.all()

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

blog/templates/blog/couse_detail.html
{% extends "blog/base_2.html" %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block style %}
    <link rel="stylesheet" href="{% static 'blog/course_detail.css' %}"> {% endblock %}
{% block content %}
    <section class="course_detail" style="background-image: url({{ course.image.url }});">
        <div class="overlay"></div>
        <div class="txt">
            <div class="heading">
                <h1> {{ course.title }}</h1>
                <p class="description">
                    {{ course.description }}
                </p>
                <div>
                    <img class="img-fluid rounded-circle" src="{{ course.instructor.user.profile.image.url }}"
                         alt="...">
                    <p style="font-size: 1.3rem;">
                        {{ course.instructor.user.first_name }} {{ course.instructor.user.last_name }}
                    </p>
                </div>

                <h6>
                    {{ course.level }}
                </h6>
                <p class="text-secondary">
                    {{ course.creationDate }}
                </p>

            </div>
        </div>

        <div style="z-index: 10" class="custom-shape-divider-bottom-1613919420">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120"
                 preserveAspectRatio="none">
                <path d="M985.66,92.83C906.67,72,823.78,31,743.84,14.19c-82.26-17.34-168.06-16.33-250.45.39-57.84,11.73-114,31.07-172,41.86A600.21,600.21,0,0,1,0,27.35V120H1200V95.8C1132.19,118.92,1055.71,111.31,985.66,92.83Z"
                      class="shape-fill"></path>
            </svg>
        </div>
    </section>

    <section class="you_will_learn container">

        <div class="title">
            <h3> WHAT YOU WILL LEARN </h3>
        </div>
        <div class="body">
            <p>
                {{ course.you_will_learn }}

            </p>
        </div>


    </section>

    <section class="sections container-fluid">
        <div>
            <h2> Sections of this Course </h2>
        </div>


        {% for section in sections %}
            {% if enroll or request.user == course.instructor.user %}
                <h4><a href="{{ section.get_absolute_url }}">  {{ section.title }}</a>
                    {% if request.user == course.instructor.user %}
                    <a style="margin-left: 20px;" href="{% url 'section-update' section.id%}"><img style=" height: 25px;width: 25px;" alt="icon" src="{% static 'blog/images/edit.png' %}"/> </a>
                    {% endif %}



                </h4>

            {% else %}
                <h4> {{ section.title }} </h4>

            {% endif %}
        {% endfor %}
        {% if request.user == course.instructor.user %}
        <h4> <a style="font-size: medium;color: #428bca; text-decoration: none;" href="{% url 'section-create' course.id%}" > <img alt="add" style=" height: 25px;width: 25px;" src="{% static 'blog/images/add.png' %}" />
            add a section ..
             </a>
        </h4>
        {% endif %}
    </section>
    {% if enroll %}

        <div class="purchase-button">
            <h4 class=" btn4"> You Already enrolled this course </h4>
        </div>


    {% else %}

        <div class="purchase-button">
            <a class="btn btn4" href="{% url 'checkout' course.id %}"><h4> Buy This Course Now</h4></a>
        </div>
    {% endif %}


    <section style="color: #00022e" class="comments container-fluid mt-5">
        <div><h2 style="margin-left: 4.5%;"> Comments </h2></div>
        <div class="container pt-3" style="border: 1px solid lightgray">
            {% for comment in comments %}
            <div class="comment pb-3">
                <div class="commenter-info" style="display: flex;flex-direction:row;" >
                    <img class="rounded-circle" src="{{ comment.user.profile.image.url }}" alt="comment">
                    <p style="font-size: 1.3rem;">
                        {{ comment.user.first_name }} {{ comment.user.last_name }}

                    </p>
                    <p
                       class="text-secondary comment-date"> -
                    {{ comment.date }}
                    </p>
                </div>

                <p style="margin-left: 3%; margin-bottom: 5px;">  {{ comment.comment }}.
                </p>
                {% if request.user == course.instructor.user %}
                <a  class="btn-reply reply"  >↪ reply to this comment</a>
                    <form class="replyForm">
                        <input type="text" style="margin-left: 5%; padding: 10px; border-radius: 10px;border: 1px solid lightslategrey; width: 60vw; " placeholder="reply ...">
                    </form>
                {% endif %}
                <br>
            </div>
            {% endfor %}
        {% if enroll %}
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button class="btn btn-primary mb-3" type="submit" id="input-submit">Send</button>

            </form>
        {% endif %}
        </div>
    </section>

    <script>
    let ph = document.querySelector('#id_comment');
    ph.placeholder = 'Add a comment ..';
    </script>

{% endblock %}

                <input type="text" style="margin-bottom: 10px; padding: 10px; border-radius: 10px;border: 1px solid lightslategrey; width: 60vw;" placeholder="add a comment ...">

blog/templates/blog/create_course.html
{% extends "blog/base_2.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'blog/Course.css' %}">
    <link rel="stylesheet" href="{% static 'blog/update_course.css' %}">
{% endblock %}
{% block content %}

    <section class="login instructor">


    <div class="container py-5" style="margin-top: 10%">
        <div class="row ">

                <div class="container">


                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <legend  style="color: #532d84;font-weight: bolder; text-align: center;font-size: 2.5rem;margin-bottom: 10%;">
                                Create your Course  </legend>
                            <div class="form">
                            {{ form|crispy }}

                            <button type="submit" class="btn btnn ">Create</button>
                            <a class="btn btnn " href="{% url 'created_courses' %}"> Cancel</a>
                            </div>
                        </form>


                </div>




        </div>
    </div>
</section>

{% endblock content %}

blog/templates/blog/create_section.html
{% extends "blog/base_2.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'blog/Course.css' %}">
    <link rel="stylesheet" href="{% static 'blog/update_course.css' %}">
{% endblock %}
{% block content %}

    <section class="login instructor">


    <div class="container py-5" style="margin-top: 10%">
        <div class="row ">

                <div class="container">


                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <legend  style="color: #532d84;font-weight: bolder; text-align: center;font-size: 2.5rem;margin-bottom: 10%;">
                                Add a new section </legend>
                            <div class="form">
                            {{ form|crispy }}

                            <button type="submit" class="btn btnn ">Create</button>
                            <a class="btn btnn " href="{% url 'created_courses' %}"> Cancel</a>
                            </div>
                        </form>


                </div>




        </div>
    </div>
</section>

{% endblock content %}

blog/templates/blog/domain.html
{% extends "blog/base_2.html" %}
{% load static %}


{% block style %} <link rel="stylesheet" href="{% static 'blog/domain.css' %}"> {% endblock %}
{% block content %}
    <section class="main-2 mx-auto">


        <div class="container  py-5 mb-5">
            <div class="row row-cols-1 row-cols-lg-2 ">
              <div class="col col1 my-auto">
                  <h2 >Chose your studying field</h2>

                  <p>Choosing a Field will provide all course that belong to it making it easy for you to find what you're looking to learn
                  </p>

              </div>
              <div class="col ">
              <img class="img-fluid" src="{% static '/blog/images/Lovepik_com-401679645-online-education-culture.png' %}" alt="...">
              </div>

            </div>
        </div>
    </section>
    <section class="header">
        <h4 class=" "> Domains </h4>
        <form onsubmit="event.preventDefault();" role="search">

            <input id="search" type="search" placeholder="Search..." autofocus required />
            <button type="submit">Go</button>
        </form>
    </section>
    <section class="Domains container-fluid">
        <div class="row row-cols-lg-4 row-cols-1">
            {% for domain in domains %}
        <article class="Domain col">
           <a href="{{domain.get_absolute_url}}"> <div>
                <img class="img-fluid" src="{{ domain.image.url }}" alt="domain">
            </div>
            <div>
                <h4 >
                    {{ domain.title }}
                </h4>
            </div></a>
        </article>
            {% endfor %}
        </div>
    </section>

{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}" alt="">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}

blog/templates/blog/update_course.html
{% extends "blog/base_2.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'blog/update_course.css' %}">
{% endblock %}
{% block content %}

    <section class="login instructor">


    <div class="container py-5" style="margin-top: 10%">
        <div class="row ">

                <div class="container">


                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <legend  style="color: #532d84;font-weight: bolder; text-align: center;font-size: 2.5rem;margin-bottom: 10%;">
                                Update your Course  </legend>
                            <div class="form">
                            {{ form|crispy }}

                            <button type="submit" class="btn btnn ">Save</button>
                            <a class="btn btnn " href="{% url 'created_courses' %}"> Cancel</a>
                            </div>
                        </form>


                </div>




        </div>
    </div>
</section>

{% endblock content %}

blog/templates/blog/update_section.html
{% extends "blog/base_2.html" %}
{% load crispy_forms_filters %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'blog/update_course.css' %}">
{% endblock %}
{% block content %}

    <section class="login instructor">


    <div class="container py-5" style="margin-top: 10%">
        <div class="row ">

                <div class="container">


                        <form method='post' enctype="multipart/form-data">
                            {% csrf_token %}
                            <legend  style="color: #532d84;font-weight: bolder; text-align: center;font-size: 2.5rem;margin-bottom: 10%;">
                                Update your Section  </legend>
                            <div class="form">
                            {{ form|crispy }}

                            <button type="submit" class="btn btnn ">Save</button>
                            <a class="btn btnn " href="{% url 'created_courses' %}"> Cancel</a>
                            </div>
                        </form>


                </div>




        </div>
    </div>
</section>

{% endblock content %}